name: symfony-starter-kit

services:
  web:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: nginx
    working_dir: /var/www/project
    volumes:
      - ../app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
      - "443:443"
    networks:
      - symfony-starter-kit

  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    platform: linux/amd64
    container_name: php
    working_dir: /var/www/project
    ports:
      - "9000:9000"
    volumes:
      - ../app:/var/www/project:rw,delegated
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - symfony-starter-kit
    environment:
      APP_ENV: dev
      APP_DEBUG: 'true'
      APP_SECRET: secret
      DATABASE_URL: postgres://postgresuser:postgrespass@postgres:5432/app

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespass
      POSTGRES_USER: postgresuser
    networks:
      - symfony-starter-kit

  node:
    image: node:19
    container_name: node
    working_dir: /var/www/project
    volumes:
      - ../app:/var/www/project
    networks:
      - symfony-starter-kit

networks:
  symfony-starter-kit:
